// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/package1/People.proto

package com.ecrr.fct.protobufgenerated;

public interface PeopleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:People)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<com.ecrr.fct.protobufgenerated.Person> 
      getPersonList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  com.ecrr.fct.protobufgenerated.Person getPerson(int index);
  /**
   * <code>repeated .Person person = 1;</code>
   */
  int getPersonCount();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  java.util.List<? extends com.ecrr.fct.protobufgenerated.PersonOrBuilder> 
      getPersonOrBuilderList();
  /**
   * <code>repeated .Person person = 1;</code>
   */
  com.ecrr.fct.protobufgenerated.PersonOrBuilder getPersonOrBuilder(
      int index);
}
