// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/People.proto

package com.ecrr.fct.protobufgenerated;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>repeated .Address address = 2;</code>
   */
  java.util.List<com.ecrr.fct.protobufgenerated.Address> 
      getAddressList();
  /**
   * <code>repeated .Address address = 2;</code>
   */
  com.ecrr.fct.protobufgenerated.Address getAddress(int index);
  /**
   * <code>repeated .Address address = 2;</code>
   */
  int getAddressCount();
  /**
   * <code>repeated .Address address = 2;</code>
   */
  java.util.List<? extends com.ecrr.fct.protobufgenerated.AddressOrBuilder> 
      getAddressOrBuilderList();
  /**
   * <code>repeated .Address address = 2;</code>
   */
  com.ecrr.fct.protobufgenerated.AddressOrBuilder getAddressOrBuilder(
      int index);

  /**
   * <code>repeated string mobile = 3;</code>
   * @return A list containing the mobile.
   */
  java.util.List<java.lang.String>
      getMobileList();
  /**
   * <code>repeated string mobile = 3;</code>
   * @return The count of mobile.
   */
  int getMobileCount();
  /**
   * <code>repeated string mobile = 3;</code>
   * @param index The index of the element to return.
   * @return The mobile at the given index.
   */
  java.lang.String getMobile(int index);
  /**
   * <code>repeated string mobile = 3;</code>
   * @param index The index of the value to return.
   * @return The bytes of the mobile at the given index.
   */
  com.google.protobuf.ByteString
      getMobileBytes(int index);

  /**
   * <code>repeated string email = 4;</code>
   * @return A list containing the email.
   */
  java.util.List<java.lang.String>
      getEmailList();
  /**
   * <code>repeated string email = 4;</code>
   * @return The count of email.
   */
  int getEmailCount();
  /**
   * <code>repeated string email = 4;</code>
   * @param index The index of the element to return.
   * @return The email at the given index.
   */
  java.lang.String getEmail(int index);
  /**
   * <code>repeated string email = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the email at the given index.
   */
  com.google.protobuf.ByteString
      getEmailBytes(int index);
}
